CREATE TABLE IF NOT EXISTS Consumers
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lastname VARCHAR(20) NOT NULL,
    firstname VARCHAR(20) NOT NULL
);
INSERT INTO Consumers (lastName, firstName)
VALUES ('Petrov', 'Ivan'),
       ('Bobrov', 'Leha');


CREATE TABLE IF NOT EXISTS Products
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productname VARCHAR(20) NOT NULL,
    price REAL
);
INSERT INTO Products (productName, price)
VALUES ('Bread', 20.2),
       ('milk', 15),
       ('ice cream', 8);

CREATE TABLE IF NOT EXISTS Purchases
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        TIMESTAMP,
    consumer_id INTEGER REFERENCES Consumers (Id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES Products (Id) ON DELETE CASCADE
);
INSERT INTO Purchases (date, consumer_id, product_id)
VALUES
    ('2020-10-19 10:23:54', 1, 2),
    ('2021-10-19 10:23:54', 1, 2),
    ('2022-10-19 10:23:54', 2, 1);
--todo доделать связь many